// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA4_jDWr_FESu1CXv8-R-MWWaQUaWQacnk',
    appId: '1:297352060294:android:def685d34121b87987a007',
    messagingSenderId: '297352060294',
    projectId: 'grofast-ondemandgroceryapp',
    databaseURL: 'https://grofast-ondemandgroceryapp-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'grofast-ondemandgroceryapp.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDz5dGyWXo23AyNlJCzUYGid6aD7YeOgSY',
    appId: '1:297352060294:ios:e4e871fab7cdee0887a007',
    messagingSenderId: '297352060294',
    projectId: 'grofast-ondemandgroceryapp',
    databaseURL: 'https://grofast-ondemandgroceryapp-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'grofast-ondemandgroceryapp.appspot.com',
    androidClientId: '297352060294-m3iqe6jo38lkitupoq0nlf8nsnthir7k.apps.googleusercontent.com',
    iosClientId: '297352060294-e7cpfgbj5nhqc9l8fqftu9gilgjqahk4.apps.googleusercontent.com',
    iosBundleId: 'com.example.onDemandGroceryStore',
  );
}
